task:
  container:
    image: node:latest
    additional_containers:
      - name: postgres
        image: postgres:11-alpine
        port: 5432
        env:
          POSTGRES_USER: forall
          POSTGRES_PASSWORD: forall
          POSTGRES_DB: forall-dev
      - name: redis
        image: redis:5-alpine
        port: 6379
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  matrix:
    - name: Typecheck
      typecheck_script: npm run typecheck
    - name: Lint
      lint_script: npm run lint
    - name: Test
      test_script: npm test
      e2e_test_script: npm run test:e2e

docker_builder:
  name: Docker
  only_if: $CIRRUS_REPO_OWNER == 'moonad' && $CIRRUS_BRANCH == 'master'
  depends_on:
    - Typecheck
    - Lint
    - Test
  env:
    DOCKER_PASSWORD: ENCRYPTED[ed0a2d6d1d1b184a4c424f8485d21a938a92b8aeb607de05a50bea2a0e07eedd5c45f02594d073409c47371a7f0f89cb]
    DOCKER_USERNAME: ENCRYPTED[876aa6e366dbec45c680ed5dd112b009bdcace5dd32599c29aa4a370e9dff0c8456ba57d438fb859863cebff3bbbf0b3]
  build_script: docker build --tag moonad/forall-server:latest .
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push moonad/forall-server:latest